### ISSUE TITLE
Spark Packages Release

### ISSUE THREAD

**Issue by brkyvz** [cloudant-labs/spark-cloudant#1]
Hi,

Thank you very much for this Spark Package. Would you be interested in making an official release to the Spark Packages Repository so that Spark users can easily access this package?
Using the sbt-spark-package plugin everything will be handled for you, and Spark users will be able to use your package in their applications by simply:
`--packages TargetHolding/pyspark-cassandra:0.1.1`
with pyspark or spark-submit.

You can simply publish the release through the plugin with the command `sbt spPublish`!

https://github.com/databricks/sbt-spark-package

Best,
Burak

**Comment by yanglei99** [comment]
Thank you for the suggestions. Will look into it. 

Yang

**Comment by mayya-sharipova** [comment]
@brkyvz Hello! I was trying to use your `sbt-spark-package` to publish it locally using `sbt spPublishLocal` command. But I ran into an issue of the mismatch in the ivy repos. `spPublicLocal` publishes it into  `.ivy2/local/com.cloudant.spark/cloudant-spark/0.1-SNAPSHOT-s_2.10/jars/cloudant-spark.jar` , while when I was trying to reference this library as a dependency in another project, it will search it as  `.ivy2/local/com.cloudant.spark/cloudant-spark_2.10/0.1-SNAPSHOT/ivys/ivy.xml`.  Any help how to resolve this issue will be appreciated!

**Comment by brkyvz** [comment]
Hi @mayya-sharipova . The `sbt-spark-package` was meant to work well with Spark, but `spPublishLocal` doesn't work well with Spark with a problem in Spark itself. You could try `publishM2` if you would like to reference it in other projects.

**Comment by mayya-sharipova** [comment]
@brkyvz Thanks very much for your reply.  I thought that `spPublicLocal` is a part of the `sbt-spark-package`. The instructions in the github say that "You may publish your package locally for testing with sbt spPublishLocal",  what is meant by this?  It seems that I can't really test locally my package in another spark application.

**Comment by yanglei99** [comment]
With the latest Spark releases (at least since 1.5.1) you can use --packages to indicate dependent jars that is published to  maven repo. This means you can publish to maven to make dependent jars available to spark-submit.

**Comment by mayya-sharipova** [comment]
The package has been added to http://spark-packages.org/package/cloudant-labs/spark-cloudant
