### ISSUE TITLE
Cloudant HTTP status 409 (document update conflicts) are logged as level INFO, should be ERROR or WARN

### ISSUE THREAD

**Issue by jtrayfield** [cloudant-labs/spark-cloudant#25]
15/12/16 14:43:23 INFO JsonStoreDataAccess: HttpResponse(409 Conflict,HttpEntity(text/plain; charset=UTF-8,{"error":"conflict","reason":"Document update conflict."}

**Comment by mayya-sharipova** [comment]
Thanks for the comment, we have already handled this in a new version. An error will be raised if the save operation was not successful.
