### ISSUE TITLE
Select statement requires the exact order of columns in python

### ISSUE THREAD

**Issue by mayya-sharipova** [cloudant-labs/spark-cloudant#29]
Not sure if it an issue with spark, or the connector, but if the schema is discovered as:
root
 |-- _id: string (nullable = true)
 |-- _rev: string (nullable = true)
 |-- cast: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- director: string (nullable = true)
 |-- genre: array (nullable = true)

n the select statement of dataframe, we should use columns with the same order, otherwise the result will be wrong.  For example:
df.select("_id", "director", "genre") produces correct results;

while
df.select("_id", "genre", "director") produces wrong results.

It is possible that this is the issue with Spark itself, and with newer versions of Spark it will be resolved.

**Comment by mayya-sharipova** [comment]
doing 
df.select(df._id, df.genre, df.director) always return right results despite the order of columns.

**Comment by HolgerKache** [comment]
@mayya-sharipova is that something we should highlight in our examples and README as well? Make sure we qualify all columns all the time?

**Comment by ykye** [comment]
if we "cache" the DataFrame by invoking `df.cache()`, everything works as expect.

**Comment by ykye** [comment]
Fixed
