### ISSUE TITLE
Propose change to configuration and others

### ISSUE THREAD

**Issue by yanglei99** [cloudant-labs/spark-cloudant#45]
1. all configuration keys for SparkConf need to start with spark.

So that it can be passed through spark-submit --conf . Otherwise it is lost

2. remove the special parameter key for schemaSampleSize as we should be using the same key for the same purpose regardless where it is set

I would also like to propose remove all none Datasource relation providers as they are too outdated

I will make change in my fork, I will leave the samples unchanged, as decisions need to be made which sample need to remove, which need to be revised based on the above changes

Thank you.

**Comment by yanglei99** [comment]
Revise to the first element, will add code to support both keys with "spark." prefix and the current key to reduce impact to the current code.

**Comment by HolgerKache** [comment]
We already removed all none datasource providers. Please see https://github.com/cloudant-labs/spark-cloudant/pull/43

Can you elaborate on the SparkConf changes?

Also, we can not accept any commits done from outside of Cloudant at this point as we have to support this project now with our internal process. Can you please follow the process as described here: https://github.com/cloudant-labs/spark-cloudant/pull/40

Especially a commit from a private fork is really problematic. Can you please create a branch off https://github.com/cloudant-labs/spark-cloudant whenever you want to commit to the project. Thank you!

**Comment by yanglei99** [comment]
The current keys, as they do not start with "spark.",  will not be passed through spark-submit (--conf). I will add the logic to check both the current key and the one with "spark." prefix so we can use spark-submit to pass in all cloudant related configuration. And these "spark." prefixed key will take precedent to all other configuration. 

I will look into the process #40 to create a branch to submit changes,   after I am done with my fork, as I need the changes to get my current work done.

Thanks.

**Comment by yanglei99** [comment]
/**
   * The sequence of the getting config
   * 1. "spark."+key in the SparkConf (as they are treated as the one passed in through spark-submit)
   * 2. key in the parameters, which is set in DF option
   * 3. key in the SparkConf, which is set in SparkConf
   * 4. default in the Config, which is set in the application.conf
   */

**Comment by HolgerKache** [comment]
@yanglei99 thanks for those details.

When you prefix parameters with "spark." please make sure to update all of the test cases and the README.md as well. We will have to take care of the existing videos and tutorials out there. Small changes like that have a big impact.

**Comment by yanglei99** [comment]
This change should not affect existing code but rather adding new capabilities. Yes, README will be revised to add this spark.$key support

**Comment by mayya-sharipova** [comment]
@yanglei99 About your proposals:
**1) All configuration keys for SparkConf need to start with spark. **
I agree with this, but to allow backward compatibility, for now we can support both configurations keys - with spark and the current ones. Do you want me to go ahead and implement this patch?

**2) remove the special parameter key for schemaSampleSize as we should be using the same key for the same purpose regardless where it is set**
Do you mean we should not have `jsonstore.rdd.schemaSampleSize`? And just to have `schemaSameSize`?

`3) Remove all other DataSource `- as Holger said, we have already implemented this.

What do you mean by "samples"? Examples? I have already cleared them. But please let me know if you think that there are some redundant examples.

**Comment by mayya-sharipova** [comment]
All the proposed changes have been implemented and merged to master
