### ISSUE TITLE
Failed to find data source: com.cloudant.spark

### ISSUE THREAD

**Issue by weijian19391** [cloudant-labs/spark-cloudant#46]
Hi 

While running the ipython example from https://github.com/cloudant-labs/spark-cloudant/blob/master/examples/ipython/python_Cloudant.ipynb, the following error occured: 

````Py4JJavaError: An error occurred while calling o60.load.
: java.lang.ClassNotFoundException: Failed to find data source: com.cloudant.spark. Please find packages at http://spark-packages.org````

Any idea why did that error occur??

**Comment by HolgerKache** [comment]
Hi @weijian19391 - are you running this iPython notebook in the Bluemix service deployed at https://console.ng.bluemix.net ? The service itself can be found in the catalog when you search for _Apache Spark_. That is where the Cloudant connector library that provides package `com.cloudant.spar`k is pre-loaded in the JVM and the class can be resolved by the iPython script. I just validated again that works as expected in the US-South Bluemix region at least.

If this is a test outside of Bluemix (your own iPython environment) you would have to make sure to bind the Cloudant Spark connector .jar to your execution environment. Fetch the version you need from https://github.com/cloudant-labs/spark-cloudant#binary-download and bind it like:

`$SPARK_HOME/spark-submit --jars cloudant-spark.jar ipython_test_Cloudant.py`

The package is not yet available on spark-packages.org (but we are working to get it up there).

**Comment by weijian19391** [comment]
Hi @HolgerKache 

I am running it outside of Bluemix, and i'm a little confused by your instructions. from what i can tell, ````ipython_test_Cloudant.py```` is the script that we are executing right? But isn't the ipython file in the format of .ipynb?

**Comment by cloudant-spark-service** [comment]
Right, so the iPython examples are there to be used in the context of Bluemix. Here is a tutorial that shows how to run these notebooks in Spark on Bluemix: https://developer.ibm.com/clouddataservices/docs/spark/tutorials-and-samples/load-and-filter-cloudant-data-with-spark/

I gave you the instructions on how to use the Python examples outside of Bluemix but don't have them for iPython. Does this post help -> http://stackoverflow.com/questions/31464845/automatically-including-jars-to-pyspark-classpath

**Comment by cloudant-spark-service** [comment]
Closing as working-by-design. Please re-open if you don't agree. Thank you!
