### ISSUE TITLE
cloudant connectivity should default to https

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#5]
It appears the cloudant connector is connecting to Cloudant over plain http.  We should probably default to https.

```
@serializable case class CloudantConfig(val host: String, val dbName: String, val indexName: String = null)(implicit val username: String, val password: String, val partitions:Int, val maxInPartition: Int, val minInPartition:Int, val requestTimeout:Long,val concurrentSave:Int, val bulkSize: Int) extends JsonStoreConfig{
  
    private lazy val dbUrl = {"http://"+ host+"/"+dbName}

    val pkField = "_id"
```
See https://github.com/cloudant/spark-cloudant/blob/5ad1034414e6071be89f4cfe4b961fcc6263ef1b/cloudant-spark-sql/src/main/scala/com/cloudant/spark/CloudantConfig.scala#L34

**Comment by HolgerKache** [comment]
Merged with https://github.com/cloudant-labs/spark-cloudant/commit/fcb91cbe75990412315145245ffe6da22dafbdcd
