### ISSUE TITLE
Make default value for schemaSampleSize = -1

### ISSUE THREAD

**Issue by mayya-sharipova** [cloudant-labs/spark-cloudant#57]
Currently, the default schemaSampleSize = 1. It means that only 1 document is used for schema detection. This leads to program crashes for many users. It would be more beneficial to make it equal to -1 to use all documents for schema detection, especially now when we don't need to load documents twice from Cloudant. This will avoid crashes, and if a user have all documents of the same schema, he/she can specify a different number using schemaSampleSize.

@ykye @yanglei99  What do you think?

**Comment by ykye** [comment]
This can avoid crashes but the default spark job might be expensive.

**Comment by mayya-sharipova** [comment]
Fixed, and merge to master
