### ISSUE TITLE
document streaming behaviour

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#60]
> Different input sources provide different guarantees, ranging from at-least once to exactly once. Read for more details.

Source: http://spark.apache.org/docs/1.5.2/streaming-programming-guide.html#fault-tolerance-semantics

I'm guessing spark-cloudant implements at-least once which will require the *application to think about how it handles duplicates especially in the case of _changes feed rewinds [1]*.  It would be good to capture this behavoir in the README so that the application can decide how it will handle duplicates.

---
[1] @willholley - have I stated this correctly?

**Comment by mayya-sharipova** [comment]
The note about duplicates has been put: https://github.com/cloudant-labs/spark-cloudant/blob/master/README.md#implementation-of-receiver.
