### ISSUE TITLE
Is it possible to use spark-cloudant to connect couchdb ?

### ISSUE THREAD

**Issue by gammaliu** [cloudant-labs/spark-cloudant#67]
As the question : Is it possible to use spark-cloudant to connect couchdb ?

Anyone knows? 

Thanks!

**Comment by mayya-sharipova** [comment]
@gammaliu Yes, you can use spark-cloudant to connect to couchdb.  You just need to set the relevant settings here: https://github.com/cloudant-labs/spark-cloudant/blob/master/examples/python/CloudantApp.py#L23-L26

For example, you can set `conf.set("cloudant.protocol","http")` if your couchdb uses `http`.
