### ISSUE TITLE
please make the binary available at spark packages

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#68]
please make the binary available at spark packages so that it is easier to add as a dependency to my spark jobs

**Comment by mayya-sharipova** [comment]
@snowch It is already available: https://spark-packages.org/package/cloudant-labs/spark-cloudant

**Comment by snowch** [comment]
@mayya-sharipova ah, thanks.  This was the first one I got when I googled spark packages cloudant: https://spark-packages.org/package/cloudant/spark-cloudant - maybe we can get this one removed?
