### ISSUE TITLE
compile issue: Please add any Spark dependencies by supplying the sparkVersion and sparkComponents

### ISSUE THREAD

**Issue by snowch** [cloudant-labs/spark-cloudant#81]
This is probably user error (I'm new to scala and sbt) but posting here just in case:

```
snowch$ sbt assembly
[info] Loading project definition from /Users/snowch/Repos/demo_2710/scala_streaming_predictor_with_cloudant/project
[info] Set current project to Movie Rating (in build file:/Users/snowch/Repos/demo_2710/scala_streaming_predictor_with_cloudant/)
[info] Compiling 1 Scala source to /Users/snowch/Repos/demo_2710/scala_streaming_predictor_with_cloudant/target/scala-2.10/classes...
[error] /Users/snowch/Repos/demo_2710/scala_streaming_predictor_with_cloudant/src/main/scala/MovieRating.scala:60: not found: type CloudantReceiver
[error]     val changes = ssc.receiverStream(new CloudantReceiver(Map(
[error]                                          ^
[error] one error found
java.lang.RuntimeException: Please add any Spark dependencies by supplying the sparkVersion and sparkComponents. Please remove: org.apache.spark:spark-core:1.6.0:provided
```
I have also posted the issue as a question to stackoverflow: http://stackoverflow.com/questions/40951106/please-add-any-spark-dependencies-by-supplying-the-sparkversion-and-sparkcompone

The code is here: https://github.com/snowch/demo_2710/tree/spark-cloudant-compile-issue/scala_streaming_predictor_with_cloudant

**Comment by snowch** [comment]
btw - this isn't urgent for me, I'm currently using MessageHub for this functionality.  Moving to Cloudant is a nice-to-have.

**Comment by mayya-sharipova** [comment]
@snowch  If you have spark-cloudant-1.6.4-s_2.10.jar in your .ivy2 directory, than you can use `"cloudant-labs" % "spark-cloudant" % "1.6.4-s_2.10" % "provided"` in your build.sbt.

The error you are getting here `not found: type CloudantReceiver` is happening because you did not import `import com.cloudant.spark.CloudantReceiver` in your `MovieRating.scala` file.

**Comment by snowch** [comment]
doh!  Thanks Mayya.
