### ISSUE TITLE
Investigate integrating this connector with Apache Bahir

### ISSUE THREAD

**Issue by ricellis** [cloudant-labs/spark-cloudant#92]
Identify the work that would be necessary to wrap/publish this connector as an [Apache Bahir](http://bahir.apache.org/#home) Spark extension.

**Comment by ricellis** [comment]
@HolgerKache to flesh this out in the coming weeks.

**Comment by HolgerKache** [comment]
1. The connector project hosted at Cloudant Labs (https://github.com/cloudant-labs/spark-cloudant) will no longer be maintained BUT remains as-is for those customers that depend on it today
 
2. The code will be copied 1:1 into Apache Bahir (https://github.com/apache/bahir)
 
3. Bahir is an open-source Apache project (http://bahir.apache.org/) and provides Spark connectors for several data and streaming sources. Bahir is NOT an IBM project and the program committee is made up of several cloud data services vendors including Databricks, Hortonworks, Yahoo!, Cloudera and others. Couchdb/Cloudant will become one of the IBM supported data sources in Apache Bahir with the contribution of our connector code.
 
4. The connector works equally for Cloudant and Couchdb and we will commit the code so it can be marketed for both. We might decide to build two connector libraries with different names for the exact same code.
5. To commit changes to our connector code in Apache Bahir, one has to be a recognized committer for Apache Bahir and follow the process described at http://bahir.apache.org/contributing/  The process includes a JIRA for every issue, a discussion in the mailing list if necessary, a branch, and a PR. The PR will get reviewed, approved, and merged by official committers only. Currently we have 3 committers from IBM (out of 37 total) but getting to committer status can be relatively fast (1 month or less).
 
6. As long as the Cloudant team has no committers to Apache Bahir we can rely on Luciano (+Christian, +Prasanth) in the to: list to review and merge our PRs.
 
7. To get the initial release of the connector added to Apache Bahir, we have to:
- provide a Maven 2 build for the code (currently we build with SBT)
- write the documentation according to the README.md template (so it can be compiled into http://bahir.apache.org/docs/spark/current/documentation/ automatically)
 
8. Apache Bahir will automatically build a release once for every new Spark release. If the Cloudant team has a need to build a point release off cycle (e.g. to support API changes in Cloudant/Couchdb or other improvements), we can request that with a proposal to the mailing list (http://bahir.apache.org/community/)
9. The Spark-aaS team (Randy Horman) will continue to migrate Spark versions and as a result will require new connector builds. Having the connector in Apache Bahir should make it easier for the Spark-aaS to a) get notified on the availability of a new connector build and b) have a more unified process in place to drive version updates into Spark-aaS. We will have to work out exactly what that process will look like between the three teams, Cloudant, Bahir, and Spark-aaS.
 
10. The IBM Bahir team will also deliver a package for the connector into https://spark-packages.org/?q=bahir. The current https://spark-packages.org/package/cloudant-labs/spark-cloudant will remain as-is for any customers who may rely on it BUT not get any future updates.
 
11. All Cloudant, DSX or IBM Spark tutorials will point at the connector in Apache Bahir once we have a first release of our connector available.
 
12. The initial set of folks who expressed interest to work on the Cloudant/Couchdb connector for Bahir are:
- Yang Lei (built the first version of the connector)
- Esteban Laver (member of the Cloudant library team with first hands-on experience)
- Daniel Linke (a 6 months intern dedicated to work on the connector starting April 1st)

Other people with experience on the code (but with limited availability at the moment):
- Mayya Sharipova (worked on the connector when in the Indexing and Integrations squad)
- Chris Snow (drives a number of requirements based on customer work)
 
13. Putting the connector into Apache Bahir does NOT transfer ownership of the connector code. We want to put the code into an open source community project mostly to get a consolidated development process, build and test infrastructure. Cloudant will have to continue to own the code with the hope that we can leverage a larger community going forward.
